all: datatypes_venn.tex qtl_example.tex qtl_pca.tex qtl_venn.tex qtl_overlap.tex

datatypes_venn.tex qtl_example.tex qtl_pca.tex qtl_venn.tex:
	ln -s ../../plots/$@ .

qtl_overlap.tex:
	ln -s ../../analysis/$@ .
